# Generated by Django 2.2.5 on 2019-09-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filecolumnmodel',
            name='dependence',
            field=models.CharField(choices=[('dependent', 'dependent'), ('independent', 'independent')], default='dependent', max_length=20),
        ),
        migrations.AddField(
            model_name='filecolumnmodel',
            name='type',
            field=models.CharField(choices=[('numeric', 'numeric'), ('categorical', 'categorical')], default='numeric', max_length=20),
        ),
    ]
