# Generated by Django 2.2.5 on 2019-09-08 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inequality', models.CharField(choices=[('>', '>'), ('>=', '>='), ('==', '=='), ('<', '<'), ('<=', '<=')], max_length=30)),
                ('value', models.FloatField()),
                ('skip_row', models.BooleanField(default=False)),
                ('new_value', models.FloatField(blank=True, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.FileColumnModel')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.UploadFileModel')),
            ],
        ),
    ]
